import React from 'react';
import NavBar from '../components/elements/NavBar';
import Footer from '../components/elements/Footer';
import TestimonialCard from '../components/elements/TestimonialCard';
import SectionTitle from '../components/elements/SectionTitle';
import MoreTools from '../components/elements/MoreTools';
import Container from '../components/layout/Container';
import Row from '../components/layout/Row';
import Column from '../components/layout/Column';
import ResponsiveHero from '../components/password-generator/client/ResponsiveHero';
import PasswordGenerator from '../components/password-generator/client/PasswordGenerator';
import PasswordGeneratorStructuredData from '../components/password-generator/StructuredData';

const faqs = [
  {
    question: 'How secure are the passwords generated by this tool?',
    answer: 'Our password generator uses cryptographically secure random number generation and creates passwords with high entropy. All generation happens locally in your browser - no passwords are sent to our servers.',
  },
  {
    question: 'What makes a password strong?',
    answer: 'A strong password should be at least 12-16 characters long, include a mix of uppercase and lowercase letters, numbers, and special symbols. Avoid using dictionary words, personal information, or predictable patterns.',
  },
  {
    question: 'Should I use different passwords for different accounts?',
    answer: 'Absolutely! Using unique passwords for each account is crucial for security. If one account is compromised, your other accounts remain safe. Consider using a password manager to store and manage your passwords.',
  },
  {
    question: 'How often should I change my passwords?',
    answer: 'Change passwords immediately if you suspect a breach. For regular maintenance, changing important passwords every 6-12 months is reasonable, especially for critical accounts like banking and email.',
  },
  {
    question: 'Is it safe to store passwords in my browser?',
    answer: 'Modern browsers have improved password security, but dedicated password managers offer better protection with features like secure sharing, breach monitoring, and cross-device sync.',
  },
  {
    question: 'What is password entropy and why does it matter?',
    answer: 'Entropy measures password randomness and unpredictability. Higher entropy means more possible combinations, making passwords exponentially harder to crack through brute force attacks.',
  },
];

const testimonials = [
  {
    avatar: '/avatars/alex.jpg',
    name: 'Alex',
    text: 'As a cybersecurity professional, I appreciate the advanced options and real-time strength analysis. This tool generates truly secure passwords!',
  },
  {
    avatar: '/avatars/linda.jpg',
    name: 'Linda',
    text: 'The interface is incredibly intuitive. I love how it explains password strength and gives specific recommendations for improvement.',
  },
  {
    avatar: '/avatars/sam.jpg',
    name: 'Sam',
    text: 'Perfect for our team\'s security training. The visual feedback helps employees understand what makes passwords secure.',
  },
  {
    avatar: '/avatars/emily.jpg',
    name: 'Emily',
    text: 'I use this daily for client accounts. The advanced customization options are exactly what I need for different security requirements.',
  },
];

const PasswordGeneratorPage: React.FC = () => {
  return (
    <>
      <PasswordGeneratorStructuredData />
      <NavBar />
      <div style={{ background: '#f7f9fb', minHeight: '100vh' }}>
        {/* Page Title */}
        <div style={{ padding: '40px 0 20px 0', textAlign: 'center' }}>
          <Container>
            <h1 style={{
              fontSize: 'clamp(2rem, 4vw, 2.5rem)',
              fontWeight: '700',
              color: '#2c3e50',
              margin: '0 0 8px 0',
              letterSpacing: '-0.02em'
            }}>
              🔐 Password Generator
            </h1>
            <p style={{
              fontSize: '1.1rem',
              color: '#64748b',
              margin: 0,
              maxWidth: '600px',
              marginLeft: 'auto',
              marginRight: 'auto'
            }}>
              Generate ultra-secure passwords with advanced customization options
            </p>
          </Container>
        </div>

        {/* Password Generator Tool */}
        <div style={{ padding: '0 0 80px 0' }} id="generator">
          <Container>
            <Row style={{ justifyContent: 'center' }}>
              <Column xs={24} lg={20}>
                <PasswordGenerator />
              </Column>
            </Row>
          </Container>
        </div>

        {/* More Tools Section */}
        <MoreTools currentPath="/password-generator" />

        {/* Security Best Practices Section */}
        <div style={{ padding: '80px 0', background: '#fff' }} id="best-practices">
          <Container>
            <SectionTitle>Password Security Best Practices</SectionTitle>
            <Row gutter={[30, 30]}>
              <Column xs={24} md={8}>
                <div style={{ 
                  background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', 
                  padding: '30px', 
                  borderRadius: '12px', 
                  height: '100%', 
                  color: 'white',
                  position: 'relative',
                  overflow: 'hidden'
                }}>
                  <div style={{
                    position: 'absolute',
                    top: '-10px',
                    right: '-10px',
                    fontSize: '60px',
                    opacity: 0.1
                  }}>🔐</div>
                  <h3 style={{ color: 'white', marginBottom: '15px', position: 'relative', zIndex: 1 }}>
                    Use Unique Passwords
                  </h3>
                  <p style={{ position: 'relative', zIndex: 1, lineHeight: '1.6' }}>
                    Never reuse passwords across different accounts. Each service should have its own unique, strong password to prevent credential stuffing attacks.
                  </p>
                </div>
              </Column>
              <Column xs={24} md={8}>
                <div style={{ 
                  background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)', 
                  padding: '30px', 
                  borderRadius: '12px', 
                  height: '100%', 
                  color: 'white',
                  position: 'relative',
                  overflow: 'hidden'
                }}>
                  <div style={{
                    position: 'absolute',
                    top: '-10px',
                    right: '-10px',
                    fontSize: '60px',
                    opacity: 0.1
                  }}>🛡️</div>
                  <h3 style={{ color: 'white', marginBottom: '15px', position: 'relative', zIndex: 1 }}>
                    Enable 2FA
                  </h3>
                  <p style={{ position: 'relative', zIndex: 1, lineHeight: '1.6' }}>
                    Add an extra layer of security with two-factor authentication. Even if your password is compromised, 2FA keeps your accounts safe.
                  </p>
                </div>
              </Column>
              <Column xs={24} md={8}>
                <div style={{ 
                  background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)', 
                  padding: '30px', 
                  borderRadius: '12px', 
                  height: '100%', 
                  color: 'white',
                  position: 'relative',
                  overflow: 'hidden'
                }}>
                  <div style={{
                    position: 'absolute',
                    top: '-10px',
                    right: '-10px',
                    fontSize: '60px',
                    opacity: 0.1
                  }}>📱</div>
                  <h3 style={{ color: 'white', marginBottom: '15px', position: 'relative', zIndex: 1 }}>
                    Use Password Managers
                  </h3>
                  <p style={{ position: 'relative', zIndex: 1, lineHeight: '1.6' }}>
                    Password managers generate, store, and autofill strong passwords. They make it easy to use unique passwords for every account.
                  </p>
                </div>
              </Column>
            </Row>
          </Container>
        </div>

        {/* FAQ Section */}
        <div style={{ background: '#f8f9fa', padding: '80px 0' }} id="faq">
          <Container>
            <SectionTitle>Frequently Asked Questions</SectionTitle>
            <div style={{ maxWidth: 800, margin: '0 auto' }}>
              {faqs.map(f => (
                <div key={f.question} style={{ 
                  marginBottom: 24, 
                  padding: 24, 
                  background: '#fff', 
                  borderRadius: 12,
                  boxShadow: '0 2px 8px rgba(0,0,0,0.05)',
                  border: '1px solid #e9ecef'
                }}>
                  <h3 style={{ 
                    color: '#2c3e50', 
                    marginBottom: 12,
                    fontSize: '16px',
                    fontWeight: '600'
                  }}>
                    {f.question}
                  </h3>
                  <p style={{ 
                    color: '#495057', 
                    margin: 0,
                    lineHeight: '1.6',
                    fontSize: '14px'
                  }}>
                    {f.answer}
                  </p>
                </div>
              ))}
            </div>
          </Container>
        </div>

        {/* Testimonials Section */}
        <div style={{ background: '#fff', padding: '80px 0' }} id="testimonials">
          <Container>
            <SectionTitle>What Security Professionals Say</SectionTitle>
            <Row gutter={[30, 30]}>
              {testimonials.map(t => (
                <Column xs={24} md={12} lg={6} key={t.name}>
                  <TestimonialCard {...t} />
                </Column>
              ))}
            </Row>
          </Container>
        </div>

        {/* Security Notice */}
        <div style={{ 
          background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
          padding: '60px 0',
          color: 'white'
        }}>
          <Container>
            <Row style={{ justifyContent: 'center' }}>
              <Column xs={24} lg={16}>
                <div style={{ textAlign: 'center' }}>
                  <h3 style={{ 
                    color: 'white', 
                    fontSize: '24px', 
                    marginBottom: '16px',
                    fontWeight: '700'
                  }}>
                    🔒 Your Privacy is Protected
                  </h3>
                  <p style={{ 
                    fontSize: '16px', 
                    lineHeight: '1.6',
                    opacity: 0.9,
                    maxWidth: '600px',
                    margin: '0 auto'
                  }}>
                    All passwords are generated locally in your browser using cryptographically secure methods. 
                    We never see, store, or transmit your passwords. Your security is our top priority.
                  </p>
                </div>
              </Column>
            </Row>
          </Container>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default PasswordGeneratorPage;